export const socialMediaFollowrs = [
  {
    id: 1,
    platform: "facebook",
    platformIcon: "./images/icon-facebook.svg",
    username: "@nathanf",
    totalFolowrs: 1987,
    todayFollowrs: 12,
  },
  {
    id: 2,
    platform: "twitter",
    platformIcon: "./images/icon-twitter.svg",
    username: " @nathanf",
    totalFolowrs: 1044,
    todayFollowrs: 12,
  },
  {
    id: 3,
    platform: "instagram",
    platformIcon: "./images/icon-instagram.svg",
    username: "@realnathanf",
    totalFolowrs: "11k",
    todayFollowrs: 1099,
  },
  {
    id: 4,
    platform: "youtube",
    platformIcon: "./images/icon-youtube.svg",
    username: "Nathan F.",
    totalFolowrs: 8239,
    todayFollowrs: 144,
  },
];

export const overviewData = [
  {
    id: 1,
    label: " Page Views",
    icon: "./images/icon-facebook.svg",
    number: "87",
    ratio: "3%",
  },
  {
    id: 2,
    state: "danger",
    label: "Likes",
    icon: "./images/icon-facebook.svg",
    number: "52",
    ratio: "2%",
  },
  {
    id: 3,
    label: "Likes",
    icon: "./images/icon-instagram.svg",
    number: "5462",
    ratio: "2257%",
  },
  {
    id: 4,
    label: "Likes",
    icon: "./images/icon-instagram.svg",
    number: "52k",
    ratio: "1375%",
  },
  {
    id: 5,
    label: "Retweets",
    icon: "./images/icon-twitter.svg",
    number: "117",
    ratio: "303%",
  },
  {
    id: 6,
    label: "Likes",
    icon: "./images/icon-twitter.svg",
    number: "507",
    ratio: "553%",
  },
  {
    id: 7,
    state: "danger",
    label: "likes",
    icon: "./images/icon-youtube.svg",
    number: "107",
    ratio: "19%",
  },
  {
    id: 8,
    state: "danger",
    label: "Total Views",
    icon: "./images/icon-youtube.svg",
    number: "1407",
    ratio: "12%",
  },
];
